# Generated by Django 5.0.6 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Write the name of the news')),
                ('created_at', models.DateTimeField(max_length=100, verbose_name='Write the time of loading this book')),
                ('author', models.CharField(max_length=100, verbose_name='Write the author')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Download the image')),
                ('description', models.TextField(verbose_name='Write the description')),
                ('music', models.FileField(blank=True, upload_to='audio/', verbose_name='Download the music')),
                ('video', models.URLField(blank=True, verbose_name='Download the link of the video')),
                ('category_book', models.CharField(choices=[('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Old Literature', 'Old Literature'), ('Autobiography', 'Autobiography')], max_length=100, verbose_name='Write the name of the book')),
                ('opinion_book', models.CharField(blank=True, choices=[('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Old Literature', 'Old Literature'), ('Autobiography', 'Autobiography')], max_length=100, verbose_name='Write your opinion about this book')),
                ('recommendation', models.CharField(blank=True, max_length=100, verbose_name='Would you recommend that book?')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
